### ISSUE TITLE
Can't compile using UE 4.25

### ISSUE THREAD

**Issue by Cryoshell99** [ProjectBorealis/PBCharacterMovement#15]
Log:

ProcessResult.StdOut:     [3/7] Module.PBCharacterMovement.cpp
ProcessResult.StdOut:     C:/Users/*******/Documents/Unreal Projects/Khsen/Plugins/HLCM/HostProject/Plugins/PBCharacterMovement/Source/PBCharacterMovement/Private/Character/PBPlayerMovement.cpp(1097): error C2248: AActor::Role: unable to access private member declared in class "AActor"
ProcessResult.StdOut: C: \ Program Files \ UE_4.25 \ Engine \ Source \ Runtime \ Engine \ Classes \ GameFramework / Actor.h (541): note: see the declaration "AActor :: Role"

**Comment by mastercoms** [comment]
You have to use the getters and setters provided instead of direct member access.

**Comment by Cryoshell99** [comment]
> You have to use the getters and setters provided instead of direct member access.

Could you make a step-by-step plan? I understand that this is arrogance on my part, but I just started to study this engine and what you said is not clear to me

**Comment by mastercoms** [comment]
Look at the Unreal Engine 4.25 release notes, and search for GetRole. It will provide instructions on how to migrate.

**Comment by AleDema** [comment]
I supposedly fixed the Role issue, but I'm getting this error: 
PBCharacterMovement/Source/PBCharacterMovement/Private/Character/PBPlayerCharacter.cpp(238): error C2027: type usage not defined 'UDamageType'

**Comment by mastercoms** [comment]
Include the damage type class http://classifier.celdevs.com/

**Comment by mastercoms** [comment]
Fixed in: https://github.com/ProjectBorealis/PBCharacterMovement/commit/04b1e7e2509e4fa58dbbbfb2e15ec7c35551fe64
